### ISSUE TITLE
Compose.yml 是不是已经删除了？

### ISSUE THREAD

**Issue by airycanon** [metrue/YoYo#34]
你好，我从中文 Readme 里看到，可以通过 docker-compose 自己部署，但是在项目中没有找到 compose.yml，请问这个文件是不是已经删除了？
我又在 Docker hub 中搜到这个项目 [yoyo_api](https://hub.docker.com/r/metrue/yoyo_api)，可以用这个部署吗？

**Comment by metrue** [comment]
@airycanon 是的，我确实已经删除了，为了保持项目的简单。

不过如果你需要的话，我可以给你我的docker compose配置，你可以参考。

**Comment by airycanon** [comment]
我从历史记录中找到了 compose.yml，不过还是麻烦你提供一下 docker compose 配置，我好做个参考，多谢。

**Comment by metrue** [comment]
@airycanon 你可以参考这个。https://gist.github.com/metrue/1141b391a6550c85193d34d85b834338
