### ISSUE TITLE
关于项目结构，提一点建议

### ISSUE THREAD

**Issue by airycanon** [metrue/YoYo#39]
按我对本项目的理解，目前分三块：
* api 由 koa 实现
* admin 管理后台，静态页面 + js
* client 客户端，静态页面 + js

在部署项目的时候，api 可以直接用 node 运行，admin 和 client 必须依赖 nginx 且分别配置 api 的 host，整个项目的入口及配置方式不一致。

建议：

不妨考虑 admin 和 client 也集成到 koa 中统一调度，路由变为 `<server_ip>/admin`、`<server_ip>/client`、`<server_ip>/api`，部署会更方便，如果需要配置域名，只需在项目中增加一个统一的 host 配置，并在前面加一个 nginx 反代即可。

因为我的 Blog 用的是 Ghost，这里参考了 Ghost 的项目结构和路由，希望我的建议可以抛砖引玉，让这个项目有好的发展。

**Comment by metrue** [comment]
@airycanon 嗯，谢谢你的建议，我会考虑的，当然，也欢迎你直接发 PR 啊。

**Comment by metrue** [comment]
@airycanon 已经把这issue放到 0.1 的 Project 中，近期会整理完成。

**Comment by airycanon** [comment]
暂时还没能力发 PR，我也是在学习，目前的想法是把 api 的 app.js 移到根目录中，另外加一个 koa-static，返回 admin 和 client 的页面，不知这样是否可行？

**Comment by metrue** [comment]
@airycanon 趁今天放假，抽出了一点时间已经做好了，一会整理一下代码merge到master来。

**Comment by metrue** [comment]
fixed by fa6bae1b7bc09000ea92fd39a83c84336473ad67

**Comment by metrue** [comment]
@airycanon 你可以帮忙 verify 一下吗？

**Comment by airycanon** [comment]
我做了如下测试，功能均正常：
* 访问 a.com/admin 和 a.com/client，admin 可以登录，client 页面可以评论，在 admin 页面可以看到
 在 a.com/client 提交的评论。
* 另写一个静态页面作为 b.com 引入 a.com/client/dist/index.js，并提交评论，在 a.com/admin 输入 b.com，可以看到在 b.com 提交的评论。

**Comment by metrue** [comment]
@airycanon nice, thanks.
