### ISSUE TITLE
I have to access it via VPN since live demo is not in China ?

### ISSUE THREAD

**Issue by windy** [metrue/YoYo#5]

**Comment by metrue** [comment]
demo在 linode 东京的机器，按理说应该没有问题的，不过感谢反馈。我看看之后要不要迁移到国内主机。

**Comment by metrue** [comment]
it's reachable in China.  live demo https://minghe.me/2017-04-18-YoYo:%E8%87%AA%E5%B7%B1%E6%89%93%E9%80%A0%E4%B8%80%E4%B8%AA%E8%AF%84%E8%AE%BA%E6%9C%8D%E5%8A%A1.html
